### PR TITLE
DataBaseService_DeleteUserLogic_ChangeToUserId

### PR DESCRIPTION
**Pull request by strannick-rodion**

### CODE REVIEW

**Review by nmamro — CHANGES_REQUESTED** [review]
After merge of previous request without me, I gonna request changes here so I can check it properly tomorrow so no one can merge it

**Review by dTarasova — APPROVED** [review]

**Review by nmamro — CHANGES_REQUESTED** [review]
It does not work, fix and don't try to push bugs to develop

**Comment by zzzloba** [comment]
Why after new user is created, their IsActive = false?

**Comment by nmamro** [comment]
Change logic of Delete in Repository, because UserId is not a primary key in UsersCredentials, so we can not just call `.Find(userId)` to find a record there

**Comment by strannick-rodion** [comment]
This work

**Pull request closed without merging**
