### PR TITLE
Kernel_MTExceptionsFix

### PR DESCRIPTION
**Pull request by nmamro**
Fixed exceptions handling all over the solution

### CODE REVIEW

**Review by Maksim-Trolina — APPROVED** [review]

**Review by dTarasova — CHANGES_REQUESTED** [review]
I still have an exception with login user that doesn't exist in database 
An unhandled exception has occurred. See browser dev tools for details

 MassTransit.ReceiveTransport[0]
      R-FAULT rabbitmq://localhost/DatabaseService 8fda0000-cd8e-708b-696d-08d7e17d5194 DTO.BrokerRequests.InternalLoginRequest DataBaseService.BrokerConsumers.LoginUserConsumer(00:00:00.0257399)

**Comment by nmamro** [comment]
> I still have an exception with login user that doesn't exist in database
> An unhandled exception has occurred. See browser dev tools for details
> 
> MassTransit.ReceiveTransport[0]
> R-FAULT rabbitmq://localhost/DatabaseService 8fda0000-cd8e-708b-696d-08d7e17d5194 DTO.BrokerRequests.InternalLoginRequest DataBaseService.BrokerConsumers.LoginUserConsumer(00:00:00.0257399)

Now it should be okay, but it returns just InternalServerException if exception occurs somewhere in the backend.
There's a problem in our exception handling inside masstransit flow, I'm currently working on that.

**Review by ifelseelif — APPROVED** [review]

**Review by Cerberous007 — APPROVED** [review]

**Review by Cerberous007 — COMMENTED** [review]
Names of pull request should be in the same style. Please, use CamelCase for your names

**Comment by nmamro** [comment]
Fixing tests

**Review by dTarasova — APPROVED** [review]

**Review by dTarasova — APPROVED** [review]

**Pull request merged**
